/**
 * Newsletter — "IA Sin Filtros"
 *
 * Weekly Spanish-language AI newsletter.
 * Generated by Claude, sent via Resend, subscribers stored in GitHub (content/subscribers.json).
 *
 * Env vars:
 *   RESEND_API_KEY
 *   RESEND_FROM_EMAIL  (e.g. newsletter@jordisegura.com — domain must be verified in Resend)
 */

import Anthropic from "@anthropic-ai/sdk";
import { Resend } from "resend";
import { fetchAllFeeds, type FeedItem } from "./scraper";

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY ?? "unset" });

export interface Subscriber {
  email: string;
  name?: string;
  subscribedAt: string;
}

/** Loads subscribers from GitHub repo (content/subscribers.json) */
export async function loadSubscribers(): Promise<Subscriber[]> {
  const owner = process.env.GITHUB_OWNER;
  const repo = process.env.GITHUB_REPO;
  const token = process.env.GITHUB_TOKEN;
  if (!owner || !repo || !token) return [];

  const res = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/contents/personal-website/content/subscribers.json`,
    { headers: { Authorization: `token ${token}`, Accept: "application/vnd.github.v3+json" } }
  );

  if (!res.ok) return [];
  const file = (await res.json()) as { content: string };
  try {
    return JSON.parse(Buffer.from(file.content, "base64").toString("utf-8"));
  } catch {
    return [];
  }
}

/** Saves a new subscriber to GitHub (content/subscribers.json) */
export async function addSubscriber(email: string, name?: string): Promise<void> {
  const owner = process.env.GITHUB_OWNER;
  const repo = process.env.GITHUB_REPO;
  const token = process.env.GITHUB_TOKEN;
  if (!owner || !repo || !token) throw new Error("GitHub env vars not set");

  const filePath = `personal-website/content/subscribers.json`;

  // Load existing
  let subscribers: Subscriber[] = [];
  let sha: string | undefined;

  const check = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`,
    { headers: { Authorization: `token ${token}`, Accept: "application/vnd.github.v3+json" } }
  );

  if (check.ok) {
    const existing = (await check.json()) as { content: string; sha: string };
    sha = existing.sha;
    try {
      subscribers = JSON.parse(Buffer.from(existing.content, "base64").toString("utf-8"));
    } catch {
      subscribers = [];
    }
  }

  // Deduplicate
  if (subscribers.some((s) => s.email === email)) return;

  subscribers.push({ email, name, subscribedAt: new Date().toISOString() });

  const payload: Record<string, string> = {
    message: `newsletter: add subscriber`,
    content: Buffer.from(JSON.stringify(subscribers, null, 2)).toString("base64"),
    branch: "main",
  };
  if (sha) payload.sha = sha;

  await fetch(
    `https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`,
    {
      method: "PUT",
      headers: {
        Authorization: `token ${token}`,
        Accept: "application/vnd.github.v3+json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload),
    }
  );
}

/** Generates a weekly newsletter using Claude */
export async function generateNewsletter(extraContext?: string): Promise<string> {
  const feeds = await fetchAllFeeds();
  const topItems = feeds.slice(0, 15);

  const feedSummary = topItems
    .map((item, i) => `${i + 1}. [${item.source}] ${item.title}\n   ${item.summary}\n   ${item.link}`)
    .join("\n\n");

  const userContent = extraContext
    ? `Contexto adicional de Jordi: ${extraContext}\n\n---\nNoticias de la semana:\n\n${feedSummary}`
    : `Noticias de la semana:\n\n${feedSummary}`;

  const msg = await anthropic.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 3000,
    system: `Eres el ghostwriter de Jordi Segura Pons para su newsletter semanal "IA Sin Filtros".

La newsletter es para profesionales de habla hispana que quieren entender la IA de forma práctica, sin tecnicismos, con perspectiva real de negocio.

Formato de la newsletter (HTML limpio para email):
1. Saludo breve y personal de Jordi (2-3 frases, tono directo y humano)
2. Sección "Esta semana en IA" — 3-4 noticias clave traducidas/resumidas al español con el punto de vista de Jordi
3. Sección "La herramienta del momento" — 1 herramienta IA útil con uso práctico
4. Cierre con CTA sutil (visitar blog, responder al email)

Genera el HTML completo del body de email (sin <html><head><body> tags — solo el contenido interno).
Usa un estilo limpio, texto negro sobre blanco, máx width 600px, fuente sans-serif.
Escribe todo en español. Tono: como un amigo que sabe mucho de IA y te cuenta lo importante.`,
    messages: [{ role: "user", content: userContent }],
  });

  const block = msg.content[0];
  if (block.type !== "text") throw new Error("Unexpected response");
  return block.text;
}

/** Sends the newsletter to all subscribers via Resend */
export async function sendNewsletter(htmlContent: string): Promise<number> {
  const resendKey = process.env.RESEND_API_KEY;
  const fromEmail = process.env.RESEND_FROM_EMAIL ?? "newsletter@jordisegura.com";
  if (!resendKey) throw new Error("RESEND_API_KEY not set");

  const resend = new Resend(resendKey);
  const subscribers = await loadSubscribers();

  if (subscribers.length === 0) throw new Error("No subscribers yet");

  const now = new Date();
  const weekNum = Math.ceil(
    (now.getDate() - now.getDay() + 1) / 7
  );
  const subject = `IA Sin Filtros #${weekNum} — ${now.toLocaleDateString("es-ES", { day: "numeric", month: "long" })}`;

  let sent = 0;
  // Send in batches of 50 (Resend free tier limit)
  const BATCH = 50;
  for (let i = 0; i < subscribers.length; i += BATCH) {
    const batch = subscribers.slice(i, i + BATCH);
    const bccEmails = batch.map((s) => s.email);

    await resend.emails.send({
      from: `Jordi Segura <${fromEmail}>`,
      to: fromEmail,
      bcc: bccEmails,
      subject,
      html: wrapInEmailTemplate(htmlContent, subject),
    });

    sent += batch.length;
  }

  return sent;
}

function wrapInEmailTemplate(body: string, subject: string): string {
  return `<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${subject}</title>
</head>
<body style="margin:0;padding:0;background:#f5f5f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 20px;">
<tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;">
  <tr><td style="padding:32px 40px 20px;border-bottom:2px solid #000;">
    <span style="font-weight:900;font-size:20px;letter-spacing:-0.5px;">JORDI.</span>
    <span style="color:#999;font-size:12px;margin-left:12px;letter-spacing:2px;text-transform:uppercase;">IA Sin Filtros</span>
  </td></tr>
  <tr><td style="padding:32px 40px;">
    ${body}
  </td></tr>
  <tr><td style="padding:24px 40px;border-top:1px solid #eee;font-size:12px;color:#999;">
    <p>Enviado por <a href="https://jordisegura.com" style="color:#000;">Jordi Segura Pons</a> · CEO CenteIA Education</p>
    <p>Para darte de baja, responde con "baja" a este email.</p>
  </td></tr>
</table>
</td></tr>
</table>
</body>
</html>`;
}
